service: flask-serverless-lambda

provider:
  name: aws
  runtime: python3.13
  region: us-west-1
  memorySize: 128
  environment:
    API_KEY: ${ssm:/flask-serverless-lambda/api-key}
plugins:
- serverless-python-requirements
- serverless-wsgi
package:
  exclude:
  - node_modules/**
  - tests/**
  - .gitignore
  - .github/
  - requirements-lint.txt
  include:
  - api/templates/**
  - api/static/**
custom:
  wsgi:
    app: api.app.app
    pythonRequirements:
      dockerizePip: true
functions:
  app:
    handler: wsgi_handler.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'
