service: flask-serverless-ai
 
provider:
 name: aws
 runtime: python3.13
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  exclude:
    - node_modules/**
    - tests/**
    - .gitignore
  include:
    - api/templates/**
custom:
 wsgi:
   app: api.app.app
   pythonRequirements:
    dockerizePip: true
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'