name: Deploy to AWS Lambda
run-name: Deploy to ${{ inputs.environment }} triggered by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deployment"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - prod

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  ENV: ${{ inputs.environment }}
  FLASK_DEBUG: 0

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'sonyasha'

    steps:
    - uses: actions/checkout@v3

    - name: Restrict production deployments to main branch
      if: ${{ inputs.environment == 'prod' && github.ref != 'refs/heads/main' }}
      run: |
        echo "❌ Production deployment is only allowed from the main branch."
        exit 1

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Install Serverless plugins
      run: |
        serverless plugin install -n serverless-wsgi
        serverless plugin install -n serverless-ssm-fetch
        serverless plugin install -n serverless-python-requirements

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to environment
      run: |
        serverless deploy --stage $ENV
