# This workflow performs linting, builds Docker container, and runs test suite for all branches
# And bandit security checks for master branch

name: Docker container test

on:
  push:


env:
  API_KEY: ${{ secrets.API_KEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-lint.txt     
    - name: Run ruff check
      run: ruff check .
    - name: Run black check
      run: black --check .
    - name: Run isort check
      run: isort --check .

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker compose build
    - name: Start the container
      run: docker compose up
    - name: Run test suite
      run: docker compose exec -T app pytest --cov=api tests/
    - name: Stop and clean up containers
      run: docker compose down

  bandit-scan:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    # Runs a pre configured Bandit scan 
    - name: Run bandit
      uses: jpetrucciani/bandit-check@master
      with:
        # only scans under this path
        path: './api'
